---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Set locale languages'
  locale_gen: name=en_US.UTF-8 state=present

- name: 'Configure WIFI'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Upgrade and update APT packages'
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600

- name: Install common packages
  action:
    apt pkg={{ item }}
    state=present
  with_items:
  - vim
  - wget
  - git
  - curl
  - rsync
  - python3
  - python3-pip

- git:
    repo: 'https://github.com/HAN-EBIG/RLS-ControllerComponent.git'
    dest: /srv/ebig-controller

- name: Install python requirements for ebig controller
  shell: /usr/bin/pip3 install -r /srv/ebig-controller/requirements.txt

- name: Copy SystemCtl unit file for ebig controller
  copy: src=./ebig-controller.service dest=/lib/systemd/system/ebig-controller.service mode=0644

- name: Enable SystemCtl script for ebig controller
  shell: systemctl daemon-reload && systemctl enable ebig-controller.service

- name: Copy systemStats.sh file
  copy: src=./sendSystemStats.sh dest=/usr/local/bin/sendSystemStats.sh mode=0774

- name: Create system stats cronjob
  cron: minute="*"
        name="Send system stats to Influx"
        cron_file="ebig-systemStats"
        user="root"
        job="/usr/local/bin/sendSystemStats.sh"

- name: 'Check if packages need to be autoremoved'
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False

- name: 'Autoremove unused packages'
  command: apt-get -y autoremove
  when: "'packages will be REMOVED' in check_autoremove.stdout"

- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
